algorithms:
  - videoseal
  - pixelseal
  - invismark
  - trustmark:
      params:
        wm_length: 100
        model_type: Q
        wm_strength: 0.75
        device: cuda
  - mbrs
  - hidden:
      params:
        runs_root: ./submodules/HiDDeN/experiments
        run_name: combined-noise
        module_path: ./submodules/HiDDeN
        device: cuda
  - sshidden:
      params:
        ckpt_path: ./submodules/stable_signature/hidden/ckpts/hidden_replicate.pth
        encoder_depth: 4
        encoder_channels: 64
        decoder_depth: 8
        decoder_channels: 64
        num_bits: 48
        attenuation: jnd
        scale_channels: False
        scaling_i: 1.
        scaling_w: 1.5
        H: 512
        W: 512
        module_path: ./submodules/stable_signature/hidden
        device: cuda
  - watermark_anything:
        scaling_w: 1.5
        wm_length: 32
        module_path: ./submodules/watermark_anything
        ckpt_path: ./model_files/watermark_anything/wam_mit.pth
        params_path: src/wibench/algorithms/watermark_anything/configs/params.json
        device: cuda
  
  
post_embed_metrics:
{% include 'mycommon/post_embed_metrics.yml' %} 
post_attack_metrics:
{% include 'mycommon/post_attack_metrics.yml' %} 
post_extract_metrics:
{% include 'mycommon/post_extract_metrics.yml' %} 


datasets:
  - MSCOCO:
      cache_dir: ./datasets/mscoco
      split: val
      sample_range: [550, 600]

attacks:
{% include 'mycommon/jpeg_vars.yml' %}

pipeline:
  result_path: /test/attack_results/COCO_first_1000/parameter_var/jpeg/methods_p1/p12
  seed: 42
  aggregators:
    - CSV:
        table_name: table
