  - vaeattack:
      device: cuda:0 # {cuda:0 by default}
  - FluxRegeneration:
      device: cuda:0 # {cuda:0 by default}
      sequential_cpu_offload: true
  - FluxRinsing:
      device: cuda:0 # {cuda:0 by default}
      sequential_cpu_offload: true
  - bm3d
  - DIP:
      device: cuda:0 # {cuda:0 if torch.cuda.is_available()}
  - VAERegeneration:
      device: cuda:0
  - AdversarialEmbedding:
      device: cuda:0
  - AdversarialEmbeddingPSNR:
      device: cuda:0
  - DiffusionRegeneration:
      device: cuda:0
  - Identity
  - JPEG:
      report_name: jpeg_80
      quality: 80
  - JPEG:
      report_name: jpeg_50
      quality: 50
  - rotate90:
      direction: counter
  - rotate:
      report_name: rotate_30
      angle: 30
  - gaussianblur:
      report_name: gaussianblur_5
      kernel_size: 5
  - gaussiannoise:
      report_name: noise_005
      sigma: 0.05
  - centercrop:
      report_name: centercrop_80
      ratio: 0.8
  - resize:
      report_name: resize_0.5
      x_ratio: 0.5
      y_ratio: 0.5
  - randomcropout:
      report_name: randomcropout_80
      ratio: 0.8
  - brightness:
      factor: 1.2
  - contrast:
      factor: 1.2
#   - DoGBlur:
#       device: cuda:0
#   - BlurDeblurFPNInception:
#       device: cuda:0
#       weights_path: /test/code/img-watermarking-test/model_files/blur_deblur/fpn_inception.h5
#   - DoGBlurDeblurFPNInception:
#       device: cuda:0
#       weights_path: /test/code/img-watermarking-test/model_files/blur_deblur/fpn_inception.h5
#   - Averaging:
#       pattern_load_path: "/test/code/img-watermarking-test/attack_resources/averaging/pattern_stable_sig.pth"
#       report_name: averaging_stable_sig
#       device: cuda:0
#   - Averaging:
#       pattern_load_path: "/test/code/img-watermarking-test/attack_resources/averaging/pattern_stegastamp.pth"
#       report_name: averaging_stegastamp
#       device: cuda:0
#   - Averaging:
#       pattern_load_path: "/test/code/img-watermarking-test/attack_resources/averaging/pattern_treering.pth"
#       report_name: averaging_treering
#       device: cuda:0
#   - FrequencyMasking:
#       normalize: True 
#   - LatentFrequencyMasking:
#       report_name: latentfrequencymasking_zero
#       mask_mode: "zero"
#       device: cuda:0
#   - LatentFrequencyMasking:
#       report_name: latentfrequencymasking_rand
#       mask_mode: "rand"
#       device: cuda:0
#   - LatentFrequencyMasking:
#       report_name: latentfrequencymasking_mean
#       mask_mode: "mean"
#       device: cuda:0
  

