  - JPEG:
      report_name: jpeg_10
      quality: 10
  - JPEG:
      report_name: jpeg_15
      quality: 15
  - JPEG:
      report_name: jpeg_20
      quality: 20
  - JPEG:
      report_name: jpeg_25
      quality: 25
  - JPEG:
      report_name: jpeg_30
      quality: 30
  - JPEG:
      report_name: jpeg_35
      quality: 35
  - JPEG:
      report_name: jpeg_40
      quality: 40
  - JPEG:
      report_name: jpeg_45
      quality: 45
  - JPEG:
      report_name: jpeg_50
      quality: 50
  - JPEG:
      report_name: jpeg_55
      quality: 55
  - JPEG:
      report_name: jpeg_60
      quality: 60
  - JPEG:
      report_name: jpeg_65
      quality: 65
  - JPEG:
      report_name: jpeg_70
      quality: 70
  - JPEG:
      report_name: jpeg_75
      quality: 75
  - JPEG:
      report_name: jpeg_80
      quality: 80
  - JPEG:
      report_name: jpeg_85
      quality: 85
  - JPEG:
      report_name: jpeg_90
      quality: 90
  